import type { Metadata } from "next";
import {Roboto} from 'next/font/google'
import "./globals.css";
import ClientProvider from "@/hoc/ClientProvider";
import Topbar from "@/components/Topbar";
import Sidebar from "@/components/Sidebar";
import { Toaster } from "@/components/ui/sonner"; 

const font = Roboto ({
  weight:['100','300','400','500','700','900'],
  subsets:['latin']
})

export const metadata: Metadata = {
  title: "Mern Advanced Auth",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${font.className} antialiased`}>
        <ClientProvider>
          <div>
            <main className="flex-1 bg-gray-50 min-h-screen">
              {children}
            </main>
          </div>
          <Toaster />
        </ClientProvider>
      </body>
    </html>
  );
}